/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/i7H5Id4a2S4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  const featuredProducts = [
    {
      id: 1,
      name: "Bamboo Cutlery Set",
      description: "Reusable and biodegradable cutlery",
      price: 12.99,
      image: "/placeholder.svg",
    },
    {
      id: 2,
      name: "Organic Cotton Tote Bag",
      description: "Durable and sustainable shopping bag",
      price: 9.99,
      image: "/placeholder.svg",
    },
    {
      id: 3,
      name: "Beeswax Food Wraps",
      description: "Reusable alternative to plastic wrap",
      price: 14.99,
      image: "/placeholder.svg",
    },
    {
      id: 4,
      name: "Bamboo Toothbrush",
      description: "Biodegradable and eco-friendly",
      price: 4.99,
      image: "/placeholder.svg",
    },
  ]
  const productCategories = [
    {
      id: 1,
      name: "Home & Kitchen",
      image: "/placeholder.svg",
    },
    {
      id: 2,
      name: "Personal Care",
      image: "/placeholder.svg",
    },
    {
      id: 3,
      name: "Apparel",
      image: "/placeholder.svg",
    },
    {
      id: 4,
      name: "Office Supplies",
      image: "/placeholder.svg",
    },
  ]
  return (
    <div className="bg-background text-foreground">
      <header className="py-12 md:py-20 bg-gradient-to-r from-primary to-primary-foreground">
        <div className="container px-4 md:px-6">
          <div className="max-w-2xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight">Discover Eco-Friendly Products</h1>
            <p className="mt-4 text-lg md:text-xl text-primary-foreground">
              Find sustainable and environmentally-friendly products for your home, office, and lifestyle.
            </p>
            <form className="mt-8 flex justify-center">
              <Input
                type="search"
                placeholder="Search for eco-friendly products..."
                className="w-full max-w-lg rounded-l-md border-0 py-2 px-4 text-lg focus:ring-2 focus:ring-primary"
              />
              <Button
                type="submit"
                className="rounded-r-md bg-primary text-primary-foreground px-6 py-2 text-lg font-medium transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary"
              >
                Search
              </Button>
            </form>
          </div>
        </div>
      </header>
      <main>
        <section className="py-12 md:py-20">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center">
              <div className="max-w-2xl text-center">
                <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Featured Eco-Friendly Products</h2>
                <p className="mt-4 text-lg md:text-xl text-muted-foreground">
                  Check out our top picks for sustainable and environmentally-friendly products.
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8 mt-8">
                {featuredProducts.map((product) => (
                  <div
                    key={product.id}
                    className="bg-card rounded-lg overflow-hidden shadow-lg transition-all hover:scale-105"
                  >
                    <img
                      src="/placeholder.svg"
                      alt={product.name}
                      width={300}
                      height={300}
                      className="w-full h-48 object-cover"
                      style={{ aspectRatio: "300/300", objectFit: "cover" }}
                    />
                    <div className="p-4">
                      <h3 className="text-xl font-bold">{product.name}</h3>
                      <p className="text-muted-foreground mt-2">{product.description}</p>
                      <div className="flex items-center justify-between mt-4">
                        <span className="text-lg font-medium">${product.price}</span>
                        <Button
                          variant="outline"
                          className="rounded-full p-2 hover:bg-primary hover:text-primary-foreground"
                        >
                          <PlusIcon className="w-5 h-5" />
                          <span className="sr-only">Add to cart</span>
                        </Button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-20 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center">
              <div className="max-w-2xl text-center">
                <h2 className="text-3xl md:text-4xl font-bold tracking-tight">Browse by Category</h2>
                <p className="mt-4 text-lg md:text-xl text-muted-foreground">
                  Explore our wide range of eco-friendly products across different categories.
                </p>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-6 mt-8">
                {productCategories.map((category) => (
                  <Link
                    key={category.id}
                    href="#"
                    className="bg-card rounded-lg overflow-hidden shadow-lg transition-all hover:scale-105"
                    prefetch={false}
                  >
                    <img
                      src="/placeholder.svg"
                      alt={category.name}
                      width={300}
                      height={300}
                      className="w-full h-40 object-cover"
                      style={{ aspectRatio: "300/300", objectFit: "cover" }}
                    />
                    <div className="p-4 text-center">
                      <h3 className="text-xl font-bold">{category.name}</h3>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="py-8 bg-primary text-primary-foreground">
        <div className="container px-4 md:px-6 flex flex-col md:flex-row items-center justify-between">
          <div className="flex items-center">
            <MountainIcon className="h-6 w-6 mr-2" />
            <span className="text-lg font-bold">Eco Emporium</span>
          </div>
          <nav className="mt-4 md:mt-0">
            <ul className="flex space-x-4">
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Home
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Products
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Categories
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  About
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  Contact
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
